"""Initial schema with all models

Revision ID: 51cbe403ade8
Revises:
Create Date: 2025-12-28 00:19:58.470091

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51cbe403ade8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "albums",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("musicbrainz_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("artist", sa.String(length=255), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("cover_art_url", sa.String(length=500), nullable=True),
        sa.Column("cached_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("albums", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_albums_musicbrainz_id"), ["musicbrainz_id"], unique=True
        )

    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("original_title", sa.String(length=255), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("poster_path", sa.String(length=255), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("cached_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_movies_tmdb_id"), ["tmdb_id"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "weeks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("week_number", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "year", "week_number", name="uq_user_year_week"),
    )
    with op.batch_alter_table("weeks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_weeks_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_weeks_year"), ["year"], unique=False)

    op.create_table(
        "week_albums",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("week_id", sa.Integer(), nullable=False),
        sa.Column("album_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("position IN (1, 2)", name="ck_album_position_valid"),
        sa.ForeignKeyConstraint(["album_id"], ["albums.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["week_id"], ["weeks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("week_id", "position", name="uq_week_album_position"),
    )
    with op.batch_alter_table("week_albums", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_week_albums_album_id"), ["album_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_week_albums_week_id"), ["week_id"], unique=False)

    op.create_table(
        "week_movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("week_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("position IN (1, 2)", name="ck_movie_position_valid"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["week_id"], ["weeks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("week_id", "position", name="uq_week_movie_position"),
    )
    with op.batch_alter_table("week_movies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_week_movies_movie_id"), ["movie_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_week_movies_week_id"), ["week_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("week_movies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_week_movies_week_id"))
        batch_op.drop_index(batch_op.f("ix_week_movies_movie_id"))

    op.drop_table("week_movies")
    with op.batch_alter_table("week_albums", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_week_albums_week_id"))
        batch_op.drop_index(batch_op.f("ix_week_albums_album_id"))

    op.drop_table("week_albums")
    with op.batch_alter_table("weeks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_weeks_year"))
        batch_op.drop_index(batch_op.f("ix_weeks_user_id"))

    op.drop_table("weeks")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_movies_tmdb_id"))

    op.drop_table("movies")
    with op.batch_alter_table("albums", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_albums_musicbrainz_id"))

    op.drop_table("albums")
    # ### end Alembic commands ###
