"""Add artist and album_artist tables

Revision ID: 80c776c19bdb
Revises: 6e9096df251a
Create Date: 2025-12-28 16:16:40.879455

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80c776c19bdb"
down_revision: str | Sequence[str] | None = "6e9096df251a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("musicbrainz_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sort_name", sa.String(length=255), nullable=True),
        sa.Column("disambiguation", sa.Text(), nullable=True),
        sa.Column("artist_type", sa.String(length=50), nullable=True),
        sa.Column("country", sa.String(length=10), nullable=True),
        sa.Column("cached_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artists", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_artists_musicbrainz_id"), ["musicbrainz_id"], unique=True
        )

    op.create_table(
        "album_artist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("album_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("join_phrase", sa.String(length=50), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("cached_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["album_id"], ["albums.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["artist_id"], ["artists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("album_artist", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_album_artist_album_id"), ["album_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_album_artist_artist_id"), ["artist_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("album_artist", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_album_artist_artist_id"))
        batch_op.drop_index(batch_op.f("ix_album_artist_album_id"))

    op.drop_table("album_artist")
    with op.batch_alter_table("artists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artists_musicbrainz_id"))

    op.drop_table("artists")
    # ### end Alembic commands ###
