"""Make weeks globally unique per calendar week

Revision ID: 4bb3bc1dc788
Revises: 80c776c19bdb
Create Date: 2025-12-29 11:58:15.044576

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "4bb3bc1dc788"
down_revision: str | Sequence[str] | None = "80c776c19bdb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    Changes week uniqueness from per-user to global. If multiple users have
    weeks for the same year/week_number, keeps the earliest created one and
    deletes the others.
    """
    conn = op.get_bind()

    # Find and remove duplicate weeks (keep earliest created_at per year/week)
    duplicates = conn.execute(
        text("""
        SELECT year, week_number
        FROM weeks
        GROUP BY year, week_number
        HAVING COUNT(*) > 1
    """)
    ).fetchall()

    for year, week_number in duplicates:
        # Get all week IDs for this year/week, ordered by created_at
        weeks = conn.execute(
            text("""
            SELECT id FROM weeks
            WHERE year = :year AND week_number = :week_number
            ORDER BY created_at ASC
        """),
            {"year": year, "week_number": week_number},
        ).fetchall()

        # Delete all but the first (earliest) one
        for (week_id,) in weeks[1:]:
            conn.execute(text("DELETE FROM weeks WHERE id = :id"), {"id": week_id})

    # Now apply constraint change
    with op.batch_alter_table("weeks", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_user_year_week"), type_="unique")
        batch_op.create_unique_constraint("uq_year_week", ["year", "week_number"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("weeks", schema=None) as batch_op:
        batch_op.drop_constraint("uq_year_week", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_user_year_week"), ["user_id", "year", "week_number"]
        )

    # ### end Alembic commands ###
