"""Add person, movie cast and crew models

Revision ID: 6e9096df251a
Revises: 51cbe403ade8
Create Date: 2025-12-28 15:11:29.364399

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e9096df251a"
down_revision: str | Sequence[str] | None = "51cbe403ade8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "people",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("profile_path", sa.String(length=255), nullable=True),
        sa.Column("known_for_department", sa.String(length=100), nullable=True),
        sa.Column("cached_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_people_tmdb_id"), ["tmdb_id"], unique=True)

    op.create_table(
        "movie_cast",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("character", sa.Text(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("cached_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("movie_cast", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_movie_cast_movie_id"), ["movie_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_movie_cast_person_id"), ["person_id"], unique=False)

    op.create_table(
        "movie_crew",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("job", sa.String(length=100), nullable=True),
        sa.Column("cached_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("movie_crew", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_movie_crew_movie_id"), ["movie_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_movie_crew_person_id"), ["person_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movie_crew", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_movie_crew_person_id"))
        batch_op.drop_index(batch_op.f("ix_movie_crew_movie_id"))

    op.drop_table("movie_crew")
    with op.batch_alter_table("movie_cast", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_movie_cast_person_id"))
        batch_op.drop_index(batch_op.f("ix_movie_cast_movie_id"))

    op.drop_table("movie_cast")
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_people_tmdb_id"))

    op.drop_table("people")
    # ### end Alembic commands ###
